# will build a C++ programme
language: cpp
os: linux
dist: xenial
sudo: require
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

# install dependencies
install:
    - git submodule update --init --recursive
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - conda activate test-environment


# prepare build process
before_script:
    - mkdir ${TRAVIS_BUILD_DIR}/build
    - cd ${TRAVIS_BUILD_DIR}/build

# build and test
script:
    # Export CC and CXX to tell cmake which compiler to use
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    # Check versions of gcc, g++ and cmake
    - gcc -v && g++ -v && cmake --version
    # Run your build commands next
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make -j2
    - make all
    - ./tests/unittests
