# will build a C++ programme
language: cpp

# define build matrix
matrix:
    include:
        # Ubuntu 16.04 Xenial Xerus
        - os: linux
          dist: xenial
          compiler: gcc
          env:
              OS_DIST=LINUX_XENIAL
        # Ubuntu 18.04 Bionic Beaver
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              OS_DIST=LINUX_BIONIC

# install dependencies
install:
    - git submodule update --init --recursive

# prepare build process
before_script:
    - mkdir ${TRAVIS_BUILD_DIR}/build
    - cd ${TRAVIS_BUILD_DIR}/build

# build and test
script:
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make -j2
    - make all
    - ./tests/unittests
